# Generated by Django 5.0 on 2024-01-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_alter_semester_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prereq",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.course",
            ),
        ),
    ]
