# Generated by Django 5.0 on 2024-01-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_resource_tgid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="resources.semester",
            ),
        ),
    ]
