# Generated by Django 5.0 on 2024-01-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_alter_course_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource",
                to="resources.course",
            ),
        ),
    ]
