# Generated by Django 5.0 on 2024-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_alter_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="tgid",
        ),
        migrations.AlterField(
            model_name="resource",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
