# Generated by Django 5.0 on 2024-01-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_remove_resource_tgid_alter_resource_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("m_id", models.PositiveBigIntegerField()),
                (
                    "mainresource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tg",
                        to="resources.resource",
                    ),
                ),
            ],
        ),
    ]
